# Generated by Django 5.1.4 on 2025-01-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50, null=True)),
                ('CategoryDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
